Fix WAxisSliderWidget and chart viewport fail to sync
emweb/wt pull request #186
Opened 2022-02-04 03:07 UTC by Apivan

2022-02-04 03:18 UTC, Apivan commented
Fix issue  https://redmine.webtoolkit.eu/issues/9719

2022-06-24 14:58 UTC, RockinRoel requested changes
Thanks for you contribution. How did you minify the source code? I think it's likely not the same minifier as we're using. I'll do the minification myself (eventually we want to switch all of Wt's JavaScript over to another minifier).

Regards,
Roel

2022-06-24 14:58 UTC, RockinRoel commented on src/js/WCartesianChart.js
> +            var sobj = o[0].WtSObj;
Typo? This should be `wtSObj`.

In combination with the other remark, this would become:

```cpp
var sobj = o.wtSObj;
```

2022-06-24 14:58 UTC, RockinRoel commented on src/js/WCartesianChart.js
>            var o = $('#' + sliders()[i]);
I'd prefer it in the non-jQuery way here (we want to get rid of our jQuery dependency eventually):

```cpp
var o = document.getElementById(sliders()[i]);
```

2022-06-27 08:29 UTC, Apivan commented
I used babel node js to minify.

2022-06-27 08:37 UTC, emweb commented
Yeah, we're using an old version of Google Closure compiler at the moment. I minified it and made another small fix (`o.wtSObj` instead of `o[0].wtSObj`) and did a manual merge, so this can be closed now.

Regards,
Roel

2022-06-27 08:37 UTC, closed without merging